CREATE DATABASE IF NOT EXISTS campauto;
USE campauto;

-- Criar tabela roles primeiro (necessária para foreign key em users)
CREATE TABLE IF NOT EXISTS roles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  description TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Inserir roles padrão
INSERT INTO roles (id, name, description) VALUES
  (1, 'MASTER', 'Acesso total ao sistema'),
  (2, 'ADMIN', 'Administrador com acesso amplo'),
  (3, 'USER', 'Usuário padrão'),
  (4, 'ALMOX', 'Almoxarifado/Estoque'),
  (5, 'CONTAB', 'Contábil')
ON DUPLICATE KEY UPDATE name=name;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  cpf VARCHAR(20) NULL,
  telefone VARCHAR(30) NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password VARCHAR(255) NULL,
  role ENUM('MASTER','USER') NOT NULL DEFAULT 'USER',
  role_id INT NULL,
  blocked TINYINT(1) DEFAULT 0,
  must_set_password TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY idx_users_role_id (role_id),
  CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS employees (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  full_name VARCHAR(190) NOT NULL,
  phone VARCHAR(30) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_employees_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS clientes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  row_hash CHAR(32) NOT NULL,
  codigo_clifor TEXT NULL,
  codigo_empresa TEXT NULL,
  data_cadastro TEXT NULL,
  cliente TEXT NULL,
  fornecedor TEXT NULL,
  funcionario TEXT NULL,
  transportadora TEXT NULL,
  tipo_pessoa TEXT NULL,
  status TEXT NULL,
  tipo_cliente TEXT NULL,
  cpf_cnpj TEXT NULL,
  razao_social TEXT NULL,
  fantasia TEXT NULL,
  site TEXT NULL,
  email TEXT NULL,
  telefone TEXT NULL,
  fax TEXT NULL,
  celular TEXT NULL,
  tipo_fisco TEXT NULL,
  cep TEXT NULL,
  endereco TEXT NULL,
  nr TEXT NULL,
  bairro TEXT NULL,
  municipio TEXT NULL,
  uf TEXT NULL,
  obs TEXT NULL,
  rg TEXT NULL,
  oe TEXT NULL,
  data_emissao TEXT NULL,
  estado_civil TEXT NULL,
  sexo TEXT NULL,
  data_nasc TEXT NULL,
  naturalidade TEXT NULL,
  dependentes TEXT NULL,
  pai TEXT NULL,
  mae TEXT NULL,
  tipo_res TEXT NULL,
  tipo_imovel TEXT NULL,
  valor_aluguel TEXT NULL,
  tempo_res TEXT NULL,
  nome_pro TEXT NULL,
  empresa_pro TEXT NULL,
  endereco_pro TEXT NULL,
  telefone_pro TEXT NULL,
  fax_pro TEXT NULL,
  tempo_pro TEXT NULL,
  carteira_trab TEXT NULL,
  renda_mensal_pro TEXT NULL,
  outros_rend TEXT NULL,
  nome_conj TEXT NULL,
  profissao_conj TEXT NULL,
  dt_nac_conj TEXT NULL,
  cpf_conj TEXT NULL,
  rg_conj TEXT NULL,
  oe_conj TEXT NULL,
  dt_emissao_conj TEXT NULL,
  empresa_conj TEXT NULL,
  endereco_conj TEXT NULL,
  telefone_conj TEXT NULL,
  fax_conj TEXT NULL,
  tempo_conj TEXT NULL,
  renda_mensal_conj TEXT NULL,
  tipo_empresa TEXT NULL,
  inscricao_municipal TEXT NULL,
  inscricao_estadual TEXT NULL,
  inscricao_suframa TEXT NULL,
  ramo_atividade TEXT NULL,
  nome_1c TEXT NULL,
  ramal_1c TEXT NULL,
  obs_1c TEXT NULL,
  nome_2c TEXT NULL,
  ramal_2c TEXT NULL,
  obs_2c TEXT NULL,
  nome_3c TEXT NULL,
  ramal_3c TEXT NULL,
  obs_3c TEXT NULL,
  codigo_convenio TEXT NULL,
  cep_cob TEXT NULL,
  endereco_cob TEXT NULL,
  nr_cob TEXT NULL,
  bairro_cob TEXT NULL,
  municipio_cob TEXT NULL,
  uf_cob TEXT NULL,
  obs_cob TEXT NULL,
  limite_credito TEXT NULL,
  vct_contrato TEXT NULL,
  cred_devolucao TEXT NULL,
  cred_mercadoria TEXT NULL,
  conceito TEXT NULL,
  ch_cod TEXT NULL,
  ch_posicao TEXT NULL,
  ch_data TEXT NULL,
  spc_cod TEXT NULL,
  spc_posicao TEXT NULL,
  spc_data TEXT NULL,
  serasa_cod TEXT NULL,
  serasa_posicao TEXT NULL,
  serasa_data TEXT NULL,
  ref_comercial_1 TEXT NULL,
  ref_comercial_2 TEXT NULL,
  ref_comercial_3 TEXT NULL,
  ref_bancaria_1 TEXT NULL,
  ref_bancaria_2 TEXT NULL,
  ref_bancaria_3 TEXT NULL,
  usuario TEXT NULL,
  foto TEXT NULL,
  assinatura TEXT NULL,
  credito TEXT NULL,
  verifica_limite TEXT NULL,
  codigo_filial TEXT NULL,
  cadastro_simples TEXT NULL,
  codigo_tabela_preco TEXT NULL,
  codigo_centro_custo TEXT NULL,
  codigo_subcentro_custo TEXT NULL,
  ultima_compra TEXT NULL,
  codigo_municipio_ibge TEXT NULL,
  codigo_condicao_pagamento TEXT NULL,
  codigo_old TEXT NULL,
  per_des TEXT NULL,
  tipo_clifor_old TEXT NULL,
  codigo_locais_cobranca TEXT NULL,
  consumidor TEXT NULL,
  saldo_inicial TEXT NULL,
  venda_futura TEXT NULL,
  vendedor TEXT NULL,
  mecanico TEXT NULL,
  terceiro TEXT NULL,
  limite_usado TEXT NULL,
  codigo_vendedor TEXT NULL,
  chave TEXT NULL,
  sessao TEXT NULL,
  tipo_desconto TEXT NULL,
  consumidor_final TEXT NULL,
  dias_venda_futura TEXT NULL,
  UNIQUE KEY uniq_row_hash (row_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS produtos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  row_hash CHAR(32) NOT NULL,
  codigo_empresa VARCHAR(255) NULL,
  codigo_produto VARCHAR(255) NULL,
  codigo_barra VARCHAR(255) NULL,
  codigo_ncm VARCHAR(255) NULL,
  codigo_cest VARCHAR(255) NULL,
  codigo_fabrica VARCHAR(255) NULL,
  codigo_referencia VARCHAR(255) NULL,
  codigo_original VARCHAR(255) NULL,
  codigo_anp VARCHAR(255) NULL,
  descricao VARCHAR(255) NULL,
  unidade VARCHAR(255) NULL,
  codigo_secao VARCHAR(255) NULL,
  nome_secao VARCHAR(255) NULL,
  codigo_marca VARCHAR(255) NULL,
  nome_marca VARCHAR(255) NULL,
  codigo_linha VARCHAR(255) NULL,
  nome_linha VARCHAR(255) NULL,
  codigo_grupo VARCHAR(255) NULL,
  nome_grupo VARCHAR(255) NULL,
  codigo_subgrupo VARCHAR(255) NULL,
  nome_subgrupo VARCHAR(255) NULL,
  tipo_produto VARCHAR(255) NULL,
  tipo_estoque VARCHAR(255) NULL,
  data_cadastro VARCHAR(255) NULL,
  observacao VARCHAR(255) NULL,
  preco_custo DECIMAL(10,2) NULL COMMENT 'Custo do produto (uso interno no orçamento)',
  credita_icms VARCHAR(255) NULL,
  credita_ipi VARCHAR(255) NULL,
  sistema VARCHAR(255) NULL,
  controle VARCHAR(255) NULL,
  imagem VARCHAR(255) NULL,
  usuario VARCHAR(255) NULL,
  UNIQUE KEY uniq_row_hash (row_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS empresas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  row_hash CHAR(32) NOT NULL,
  nome_fantasia VARCHAR(255) NULL,
  razao_social VARCHAR(255) NULL,
  cnpj VARCHAR(255) NULL,
  endereco VARCHAR(255) NULL,
  cep VARCHAR(10) NULL,
  email VARCHAR(255) NULL,
  cidade VARCHAR(255) NULL,
  telefone VARCHAR(255) NULL,
  estado VARCHAR(2) NULL,
  data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_row_hash (row_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS orcamentos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  row_hash CHAR(32) NOT NULL,
  numero_sequencial INT NOT NULL,
  cliente_id INT NULL,
  empresa_id INT NULL,
  veiculo_id INT NULL,
  data DATE NOT NULL,
  prazo_entrega VARCHAR(255) NULL,
  validade VARCHAR(255) NULL,
  status VARCHAR(50) NULL DEFAULT 'Cotação',
  observacoes_internas TEXT NULL,
  observacoes_cliente TEXT NULL,
  json_itens JSON NULL,
  subtotal DECIMAL(10,2) NULL DEFAULT 0.00,
  desconto DECIMAL(10,2) NULL DEFAULT 0.00,
  total DECIMAL(10,2) NULL DEFAULT 0.00,
  usuario_id INT NULL,
  data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_row_hash (row_hash),
  UNIQUE KEY uniq_numero_sequencial (numero_sequencial),
  KEY idx_cliente (cliente_id),
  KEY idx_empresa (empresa_id),
  KEY idx_status (status),
  KEY idx_data (data)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO users (name, email, password, role, role_id)
SELECT 'MASTER', 'master@campauto.com', SHA2('Master@123', 256), 'MASTER', 1
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'master@campauto.com');
