CREATE DATABASE IF NOT EXISTS campauto;
USE campauto;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  cpf VARCHAR(20) NULL,
  telefone VARCHAR(30) NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password VARCHAR(64) NOT NULL,
  role ENUM('MASTER','USER') NOT NULL DEFAULT 'USER',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS employees (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  full_name VARCHAR(190) NOT NULL,
  phone VARCHAR(30) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_employees_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS clientes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  row_hash CHAR(32) NOT NULL,
  codigo_clifor VARCHAR(255) NULL,
  codigo_empresa VARCHAR(255) NULL,
  data_cadastro VARCHAR(255) NULL,
  cliente VARCHAR(255) NULL,
  fornecedor VARCHAR(255) NULL,
  funcionario VARCHAR(255) NULL,
  transportadora VARCHAR(255) NULL,
  tipo_pessoa VARCHAR(255) NULL,
  status VARCHAR(255) NULL,
  tipo_cliente VARCHAR(255) NULL,
  cpf_cnpj VARCHAR(255) NULL,
  razao_social VARCHAR(255) NULL,
  fantasia VARCHAR(255) NULL,
  site VARCHAR(255) NULL,
  email VARCHAR(255) NULL,
  telefone VARCHAR(255) NULL,
  fax VARCHAR(255) NULL,
  celular VARCHAR(255) NULL,
  tipo_fisco VARCHAR(255) NULL,
  cep VARCHAR(255) NULL,
  endereco VARCHAR(255) NULL,
  nr VARCHAR(255) NULL,
  bairro VARCHAR(255) NULL,
  municipio VARCHAR(255) NULL,
  uf VARCHAR(255) NULL,
  obs VARCHAR(255) NULL,
  rg VARCHAR(255) NULL,
  oe VARCHAR(255) NULL,
  data_emissao VARCHAR(255) NULL,
  estado_civil VARCHAR(255) NULL,
  sexo VARCHAR(255) NULL,
  data_nasc VARCHAR(255) NULL,
  naturalidade VARCHAR(255) NULL,
  dependentes VARCHAR(255) NULL,
  pai VARCHAR(255) NULL,
  mae VARCHAR(255) NULL,
  tipo_res VARCHAR(255) NULL,
  tipo_imovel VARCHAR(255) NULL,
  valor_aluguel VARCHAR(255) NULL,
  tempo_res VARCHAR(255) NULL,
  nome_pro VARCHAR(255) NULL,
  empresa_pro VARCHAR(255) NULL,
  endereco_pro VARCHAR(255) NULL,
  telefone_pro VARCHAR(255) NULL,
  fax_pro VARCHAR(255) NULL,
  tempo_pro VARCHAR(255) NULL,
  carteira_trab VARCHAR(255) NULL,
  renda_mensal_pro VARCHAR(255) NULL,
  outros_rend VARCHAR(255) NULL,
  nome_conj VARCHAR(255) NULL,
  profissao_conj VARCHAR(255) NULL,
  dt_nac_conj VARCHAR(255) NULL,
  cpf_conj VARCHAR(255) NULL,
  rg_conj VARCHAR(255) NULL,
  oe_conj VARCHAR(255) NULL,
  dt_emissao_conj VARCHAR(255) NULL,
  empresa_conj VARCHAR(255) NULL,
  endereco_conj VARCHAR(255) NULL,
  telefone_conj VARCHAR(255) NULL,
  fax_conj VARCHAR(255) NULL,
  tempo_conj VARCHAR(255) NULL,
  renda_mensal_conj VARCHAR(255) NULL,
  tipo_empresa VARCHAR(255) NULL,
  inscricao_municipal VARCHAR(255) NULL,
  inscricao_estadual VARCHAR(255) NULL,
  inscricao_suframa VARCHAR(255) NULL,
  ramo_atividade VARCHAR(255) NULL,
  nome_1c VARCHAR(255) NULL,
  ramal_1c VARCHAR(255) NULL,
  obs_1c VARCHAR(255) NULL,
  nome_2c VARCHAR(255) NULL,
  ramal_2c VARCHAR(255) NULL,
  obs_2c VARCHAR(255) NULL,
  nome_3c VARCHAR(255) NULL,
  ramal_3c VARCHAR(255) NULL,
  obs_3c VARCHAR(255) NULL,
  codigo_convenio VARCHAR(255) NULL,
  cep_cob VARCHAR(255) NULL,
  endereco_cob VARCHAR(255) NULL,
  nr_cob VARCHAR(255) NULL,
  bairro_cob VARCHAR(255) NULL,
  municipio_cob VARCHAR(255) NULL,
  uf_cob VARCHAR(255) NULL,
  obs_cob VARCHAR(255) NULL,
  limite_credito VARCHAR(255) NULL,
  vct_contrato VARCHAR(255) NULL,
  cred_devolucao VARCHAR(255) NULL,
  cred_mercadoria VARCHAR(255) NULL,
  conceito VARCHAR(255) NULL,
  ch_cod VARCHAR(255) NULL,
  ch_posicao VARCHAR(255) NULL,
  ch_data VARCHAR(255) NULL,
  spc_cod VARCHAR(255) NULL,
  spc_posicao VARCHAR(255) NULL,
  spc_data VARCHAR(255) NULL,
  serasa_cod VARCHAR(255) NULL,
  serasa_posicao VARCHAR(255) NULL,
  serasa_data VARCHAR(255) NULL,
  ref_comercial_1 VARCHAR(255) NULL,
  ref_comercial_2 VARCHAR(255) NULL,
  ref_comercial_3 VARCHAR(255) NULL,
  ref_bancaria_1 VARCHAR(255) NULL,
  ref_bancaria_2 VARCHAR(255) NULL,
  ref_bancaria_3 VARCHAR(255) NULL,
  usuario VARCHAR(255) NULL,
  foto VARCHAR(255) NULL,
  assinatura VARCHAR(255) NULL,
  credito VARCHAR(255) NULL,
  verifica_limite VARCHAR(255) NULL,
  codigo_filial VARCHAR(255) NULL,
  cadastro_simples VARCHAR(255) NULL,
  codigo_tabela_preco VARCHAR(255) NULL,
  codigo_centro_custo VARCHAR(255) NULL,
  codigo_subcentro_custo VARCHAR(255) NULL,
  ultima_compra VARCHAR(255) NULL,
  codigo_municipio_ibge VARCHAR(255) NULL,
  codigo_condicao_pagamento VARCHAR(255) NULL,
  codigo_old VARCHAR(255) NULL,
  per_des VARCHAR(255) NULL,
  tipo_clifor_old VARCHAR(255) NULL,
  codigo_locais_cobranca VARCHAR(255) NULL,
  consumidor VARCHAR(255) NULL,
  saldo_inicial VARCHAR(255) NULL,
  venda_futura VARCHAR(255) NULL,
  vendedor VARCHAR(255) NULL,
  mecanico VARCHAR(255) NULL,
  terceiro VARCHAR(255) NULL,
  limite_usado VARCHAR(255) NULL,
  codigo_vendedor VARCHAR(255) NULL,
  chave VARCHAR(255) NULL,
  sessao VARCHAR(255) NULL,
  tipo_desconto VARCHAR(255) NULL,
  consumidor_final VARCHAR(255) NULL,
  dias_venda_futura VARCHAR(255) NULL,
  UNIQUE KEY uniq_row_hash (row_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS produtos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  row_hash CHAR(32) NOT NULL,
  codigo_empresa VARCHAR(255) NULL,
  codigo_produto VARCHAR(255) NULL,
  codigo_barra VARCHAR(255) NULL,
  codigo_ncm VARCHAR(255) NULL,
  codigo_cest VARCHAR(255) NULL,
  codigo_fabrica VARCHAR(255) NULL,
  codigo_referencia VARCHAR(255) NULL,
  codigo_original VARCHAR(255) NULL,
  codigo_anp VARCHAR(255) NULL,
  descricao VARCHAR(255) NULL,
  unidade VARCHAR(255) NULL,
  codigo_secao VARCHAR(255) NULL,
  nome_secao VARCHAR(255) NULL,
  codigo_marca VARCHAR(255) NULL,
  nome_marca VARCHAR(255) NULL,
  codigo_linha VARCHAR(255) NULL,
  nome_linha VARCHAR(255) NULL,
  codigo_grupo VARCHAR(255) NULL,
  nome_grupo VARCHAR(255) NULL,
  codigo_subgrupo VARCHAR(255) NULL,
  nome_subgrupo VARCHAR(255) NULL,
  tipo_produto VARCHAR(255) NULL,
  tipo_estoque VARCHAR(255) NULL,
  data_cadastro VARCHAR(255) NULL,
  observacao VARCHAR(255) NULL,
  credita_icms VARCHAR(255) NULL,
  credita_ipi VARCHAR(255) NULL,
  sistema VARCHAR(255) NULL,
  controle VARCHAR(255) NULL,
  imagem VARCHAR(255) NULL,
  usuario VARCHAR(255) NULL,
  UNIQUE KEY uniq_row_hash (row_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS empresas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  row_hash CHAR(32) NOT NULL,
  nome_fantasia VARCHAR(255) NULL,
  razao_social VARCHAR(255) NULL,
  cnpj VARCHAR(255) NULL,
  endereco VARCHAR(255) NULL,
  cep VARCHAR(10) NULL,
  email VARCHAR(255) NULL,
  cidade VARCHAR(255) NULL,
  telefone VARCHAR(255) NULL,
  estado VARCHAR(2) NULL,
  data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_row_hash (row_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS orcamentos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  row_hash CHAR(32) NOT NULL,
  numero_sequencial INT NOT NULL,
  cliente_id INT NULL,
  empresa_id INT NULL,
  veiculo_id INT NULL,
  data DATE NOT NULL,
  prazo_entrega VARCHAR(255) NULL,
  validade VARCHAR(255) NULL,
  status VARCHAR(50) NULL DEFAULT 'Cotação',
  observacoes_internas TEXT NULL,
  observacoes_cliente TEXT NULL,
  json_itens JSON NULL,
  subtotal DECIMAL(10,2) NULL DEFAULT 0.00,
  desconto DECIMAL(10,2) NULL DEFAULT 0.00,
  total DECIMAL(10,2) NULL DEFAULT 0.00,
  usuario_id INT NULL,
  data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_row_hash (row_hash),
  UNIQUE KEY uniq_numero_sequencial (numero_sequencial),
  KEY idx_cliente (cliente_id),
  KEY idx_empresa (empresa_id),
  KEY idx_status (status),
  KEY idx_data (data)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO users (name, email, password, role)
SELECT 'MASTER', 'master@campauto.com', SHA2('Master@123', 256), 'MASTER'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'master@campauto.com');
