CREATE DATABASE IF NOT EXISTS campauto;
USE campauto;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  cpf VARCHAR(20) NULL,
  telefone VARCHAR(30) NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password VARCHAR(64) NOT NULL,
  role ENUM('MASTER','USER') NOT NULL DEFAULT 'USER',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS employees (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  full_name VARCHAR(190) NOT NULL,
  phone VARCHAR(30) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_employees_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO users (name, email, password, role)
SELECT 'MASTER', 'master@campauto.com', SHA2('Master@123', 256), 'MASTER'
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'master@campauto.com');
